validPickaxeBlocks:
  - STONE
  - STONE_BRICKS
  - MOSSY_STONE_BRICKS
  - COBBLESTONE
  - MOSSY_COBBLESTONE
  - GRANITE
  -  POLISHED_GRANITE
  - DIORITE
  - POLISHED_DIORITE
  - ANDESITE
  - POLISHED_ANDESITE
  - DEEPSLATE
  - COBBLED_DEEPSLATE
  - POLISHED_DEEPSLATE
  - DEEPSLATE_BRICKS
  - CRACKED_DEEPSLATE_BRICKS
  - DEEPSLATE_TILES
  - CRACKED_DEEPSLATE_TILES
  - BRICKS
  - TUFF
  - PACKED_MUD
  - MUD_BRICKS
  - SANDSTONE
  - CHISELED_SANDSTONE
  - SMOOTH_SANDSTONE
  - CUT_SANDSTONE
  - RED_SANDSTONE
  - CHISELED_RED_SANDSTONE
  - SMOOTH_RED_SANDSTONE
  - CUT_RED_SANDSTONE
  - PRISMARINE
  - PRISMARINE_BRICKS
  - DARK_PRISMARINE
  - NETHERRACK
  - NETHER_BRICKS
  - CRACKED_NETHER_BRICKS
  - CHISELED_NETHER_BRICKS
  - RED_NETHER_BRICKS
  - BASALT
  - BLACKSTONE
  - CHISELED_POLISHED_BLACKSTONE
  - POLISHED_BLACKSTONE
  - POLISHED_BLACKSTONE_BRICKS
  - CRACKED_POLISHED_BLACKSTONE_BRICKS
  - END_STONE
  - END_STONE_BRICKS
  - PURPUR_BLOCK
  - PURPUR_PILLAR

validShovelBlocks:
  - DIRT
  - GRASS_BLOCK
  - SAND
  - PODZOL
  - MYCELIUM
  - DIRT_PATH
  - COARSE_DIRT
  - ROOTED_DIRT
  - FARM_LAND
  - MUD
  - CLAY
  - GRAVEL
  - RED_SAND
  - SNOW_BLOCK
  - MOSS_BLOCK

validTimberBlocks:
  - OAK_LOG
  - STRIPPED_OAK_LOG
  - SPRUCE_LOG
  - STRIPPED_SPRUCE_LOG
  - BIRCH_LOG
  - STRIPPED_BIRCH_LOG
  - JUNGLE_LOG
  - STRIPPED_JUNGLE_LOG
  - ACACIA_LOG
  - STRIPPED_ACACIA_LOG
  - DARK_OAK_LOG
  - STRIPPED_DARK_OAK_LOG
  - MANGROVE_LOG
  - STRIPPED_MANGROVE_LOG
  - CHERRY_LOG
  - STRIPPED_CHERRY_LOG